language: minimal
services: docker

branches:
    only:
        - main
        - /^release-[0-9]+\..*$/

# addons:
#     sonarcloud:
#         organization: 'open-cluster-management'
#         token:
#             secure: 'lQvHiDIy2YlV2uCSMEc7qavaW8xfBKG5FF4M4+8i7VScxlxY95RNHDnxqYr429uMQN5JSSJIKupEGgKRs7xmbd20u1+EAHePA7EBRlnj2PFRl+F4gDSpkpDpXZRDGVejpnOOp03XoX30Q7IJqDo6XuEJEQU0UwiGKZZ0g7NhnyUb3pd/3A14XW7reYr73DwDt3JC7VuaYvq5GvR8w/BSchFgeAnNSVb8GiNZbwNCZZw7jbGrDKQq5X+lDs/7glfc9RYycvLZAk2mu61T5yUR5QhUJTfpBFzksGhuH6boUIgdvcGNTay8yo13lq+7zY0kps3hT7X/z8HH1lnHrUSgsw8R+KbJWMU9AiSVvIYHAS+G1LM3OmHw0+PyBmEQeCgvaze2B/V2ci/p/M4nLEvSd727PNxv9kdadfIKIoUEbNp4CgFm5yJJoF3PnmTy/3CKPA1PesEXp6oefeWbLE/v9Dd9orMa0mXRzECiwa8BmOKpmID+85nEYl8VWatGUKiWZFbmuW/CSQKlZTCcoHOJQE3WcA/SUJGzJ7PyH5R5IHe8Yf+SyGSUZylXL+Z7cqak1sbPhBTNiz+HKNyTLRTUHsac4g6q2RO6jeOTe5gT5U2d+WFfkcbOB7rv+Qr6QZFJdiZLTp6+XsvDhE1oN6yaPAcPVFBdoBg0YFwp31Bp+jo='

env:
    global:
        - OS=linux
        - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"

before_script:
    - travis_retry timeout 2m make init

jobs:
    include:
        - stage: Build and test
          name: 'Run tests, lint, and prettier check'
          if: type != cron
          language: node_js
          node_js: '12'
          install: npm ci
          script:
              - set -e
              - npm run lint
              - npm run check
              - npm test
              # - make sonar/js/jest-init
              # - make sonar/js
        - name: 'Build docker image and push it to quay'
          if: type != cron
          script:
              - set -e
              - travis_retry timeout 2m docker pull registry.access.redhat.com/ubi8/nodejs-12
              - travis_retry timeout 2m docker pull registry.access.redhat.com/ubi8/ubi-minimal
              - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
              - make component/build
              - if [ "$DOCKER_PASS" != "" ]; then make component/push ; else echo "No DOCKER_PASS. Skipping image push."; fi

        - stage: fast forward commits to release branch
          if: type = push AND branch =~ /^main$/
          script: make release-ff

        - stage: update release manifest
          if: type = push AND branch =~ /^release-[0-9]+\..*$/
          script: make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}

        - stage: Automated Dependency Upgrade
          if: type = cron AND branch = main
          language: node_js
          node_js: '12'
          install: echo skip install
          script:
              - set -e
              - git remote remove origin
              - git remote add origin https://${GITHUB_TOKEN}@github.com/@open-cluster-management/search-ui.git > /dev/null 2>&1
              - git checkout main
              - npm ci
              - npm run update
              - npm run build
              - git config --global user.email "travis@travis-ci.org"
              - git config --global user.name "Travis CI"
              - git add -u :/
              - set +e
              - git commit -m "fix(deps) - upgrade dependencies"
              - if [ $? -eq 0 ]; then git push origin main; fi
